version: '3'

volumes:
  learn-mydumper-mysql:
    name: learn-mydumper-mysql

networks:
  learn-mydumper:
    name: learn-mydumper

services:
  mysql:
    container_name: learn-mydumper-mysql
    image: mysql:8.0
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=app01
      - MYSQL_ROOT_PASSWORD=mypass
    volumes:
      - learn-mydumper-mysql:/var/lib/mysql/
    networks:
      - learn-mydumper
